version: '3'

services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    networks:
      - modoboa

  rq:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      PYTHONPATH: ".."
      DB: "SQLITE"
      DEBUG: "True"
      REDIS_HOST: redis
    command: >
      sh -c "cd test_project; python3 manage.py rqworker dkim modoboa"
    volumes:
      - .:/code
    networks:
      - modoboa

  api:
    container_name: modoboa_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8000:8000
    environment:
      PYTHONPATH: ".."
      DB: "SQLITE"
      DEBUG: "True"
      REDIS_HOST: redis
    command: >
      sh -c "cd test_project
             python3 manage.py migrate
             python3 manage.py load_initial_data
             django-admin compilemessages
             python3 manage.py runserver 0:8000"
    volumes:
      - .:/code
    networks:
      - modoboa

  front:
    container_name: modoboa_front
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile.front.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend/:/home/node/
    command: "yarn dev --host"
    environment:
      DOCKER: "yes"
    depends_on:
      - api
    networks:
      - modoboa

networks:
  name: modoboa
      name: modoboa
