FROM node:20.11-alpine

ENV HOME=/home/node/

RUN apk add --no-cache --update gettext \
    && rm -rf /var/cache/apk/*

RUN addgroup -S node && adduser -S node -G node

USER node

COPY --chown=node:node . $HOME

WORKDIR $HOME

RUN yarn install
